version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGTZ: 'Europe/Moscow'
      TZ: 'Europe/Moscow'
    ports:
      - "54321:5432"
    volumes:
      - pgsql-data:/var/lib/postgresql/data

volumes:
  pgsql-data:
    driver: local